/*query*/
SPOOL "C:\Users\admin\Documents\DBMS
L\Exp12\deposit_urk20ai1041_1.txt"SET SERVEROUTPUT ON;
SET LINESIZE 90;
SET PAGESIZE 24;
TTITLE CENTER 'DEPOSIT DETAILS' SKIP 1-
RIGHT 'Page: ' FORMAT 9 SQL.PNO SKIP 2;
BTITLE CENTER 'BANK DETAILS';
COLUMN accno FORMAT 9,999;
COLUMN cname FORMAT a20 HEADING 'CUSTOMER NAME';
COLUMN salary FORMAT 9,99,999.99;
SELECT * from
deposit_urk20ai1041 WHERE
bname = 'Coimbatore';SPOOL
OFF
CLEAR COLUMN;
/*query*/
SPOOL "C:\Users\admin\Documents\DBMS
L\Exp12\deposit_urk20ai1041_2.txt"SET SERVEROUTPUT ON;
SET LINESIZE 90;
SET PAGESIZE 24;
TTITLE CENTER 'DEPOSIT DETAILS' SKIP 1-
RIGHT 'Page: ' FORMAT 9 SQL.PNO SKIP 2;
BTITLE CENTER 'BANK DETAILS';
COLUMN accno FORMAT 9,999;
COLUMN cname FORMAT a20 HEADING 'CUSTOMER NAME';
COLUMN salary FORMAT 9,99,999.99;
SELECT bname, MAX(amount) amount FROM
deposit_urk20ai1041GROUP BY bname;
SPOOL OFF
CLEAR COLUMN;
/*query*/
SPOOL "C:\Users\admin\Documents\DBMS
L\Exp12\deposit_urk20ai1041_3.txt"SET SERVEROUTPUT ON;
SET LINESIZE 90;
SET PAGESIZE 24;
TTITLE CENTER 'DEPOSIT DETAILS' SKIP 1-
RIGHT 'Page: ' FORMAT 9 SQL.PNO SKIP 2;
BTITLE CENTER 'BANK DETAILS';
COLUMN accno FORMAT 9,999;
COLUMN cname FORMAT a20 HEADING 'CUSTOMER NAME';
COLUMN salary FORMAT 9,99,999.99;
SELECT a.accno, a.bname, a.amount FROM deposit_urk20ai1041 a
INNER JOIN
(SELECT accno, max(amount) amount FROM deposit_urk20ai1041 GROUP BY
accno) bON a.accno = b.accno AND a.amount = b.amount;
SPOOL OFF
CLEAR COLUMN;

/*query*/
SPOOL "C:\Users\admin\Documents\DBMS
L\Exp12\deposit_urk20ai1041_4.txt"SET SERVEROUTPUT ON;
SET LINESIZE 90;
SET PAGESIZE 24;
TTITLE CENTER 'DEPOSIT DETAILS' SKIP 1-
RIGHT 'Page: ' FORMAT 9 SQL.PNO SKIP 2;
BTITLE CENTER 'BANK DETAILS';
COLUMN accno FORMAT 9,999;
COLUMN cname FORMAT a20 HEADING 'CUSTOMER NAME';
COLUMN salary FORMAT 9,99,999.99;
SELECT * FROM
(SELECT * from
deposit_urk20ai1041ORDER
BY amount desc) WHERE
ROWNUM <=5; SPOOL OFF
CLEAR COLUMN;
/*query*/
SPOOL "C:\Users\admin\Documents\DBMS L\Exp12\deposit_urk20ai1041_5.txt"
SET SERVEROUTPUT ON;
SET LINESIZE 90;
SET PAGESIZE 24;
TTITLE CENTER 'DEPOSIT DETAILS' SKIP 1-
RIGHT 'Page: ' FORMAT 9 SQL.PNO SKIP 2;
BTITLE CENTER 'BANK DETAILS';
COLUMN accno FORMAT 9,999;
COLUMN cname FORMAT a20 HEADING 'CUSTOMER NAME';
COLUMN salary FORMAT 9,99,999.99;
SELECT * FROM deposit_urk20ai1041 WHERE adate > '1-
dec-95';SPOOL OFF
CLEAR COLUMN;
